[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = ["crates/*", "examples/*", "xtask"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
version = "0.6.0"
rust-version = "1.85"

[workspace.dependencies]
bitflags = { version = "2.8.0", features = ["serde"] }
derive-new = { version = "0.6.0", default-features = false }
derive_more = { version = "1", default-features = false }
log = { default-features = false, version = "0.4.22" }

fnv = "1"
serde = { version = "1.0.204", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = { version = "1.0.119", default-features = false }
toml = "0.8.22"
variadics_please = "1"

dashmap = "5.5.3"
hashbrown = "0.14.5"
smallvec = { version = "1", features = ["union", "const_generics"] }
spin = { version = "0.9.8", features = ["mutex", "spin_mutex"] }

rand = { version = "0.9.0", default-features = false, features = [
    "std_rng",
] } # std_rng is for no_std

async-channel = "2.3"
dirs = "5.0.1"
md5 = "0.7.0"
sanitize-filename = "0.5"
wasm-bindgen-futures = "0.4.45"
weak-table = "0.3"
web-time = "1.1.0"
embassy-time = { version = "0.4.0", default-features = false }

# Testing
rstest = "0.19.0"
serial_test = "3.1.1"

bytemuck = "1.16.1"
half = { version = "2.5", features = [
    "alloc",
    "num-traits",
    "serde",
], default-features = false }
num-traits = { version = "0.2.19", default-features = false, features = [
    "libm",
] } # libm is for no_std

cfg-if = "1.0.0"
darling = "0.20.10"
ident_case = "1"
paste = "1.0.15"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits", "visit-mut"] }

tracy-client = { version = "0.18.0" }

### For xtask crate ###
strum = { version = "0.26.3", features = ["derive"] }
tracel-xtask = { version = "=1.1.9" }

portable-atomic = { version = "1.10", default-features = false, features = [
    "serde",
] }
pretty_assertions = "1.4"

# Async
embassy-futures = { version = "0.1.1" }                        # for no-std
futures-lite = { version = "2.3.0", default-features = false }

[profile.dev]
debug = 0     # Speed up compilation time and not necessary.
opt-level = 0
