[package]
name = "permute-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cubecl = { path = "../../crates/cubecl", version = "=0.9.0-pre.3" }
cubecl-core = { path = "../../crates/cubecl-core", default-features = false }
cubecl-std = { path = "../../crates/cubecl-std", default-features = false }


[features]
default = []
wgpu = ["cubecl/wgpu"]
cuda = ["cubecl/cuda"]
